token: int             lineNumber: 1	  Type:	  Fundamental type
token: main            lineNumber: 1	  Type:	  Identifier
token: (               lineNumber: 1	  Type:	  Separating Character
token: )               lineNumber: 1	  Type:	  Separating Character
token: {               lineNumber: 1	  Type:	  Separating Character
token: int             lineNumber: 2	  Type:	  Fundamental type
token: x               lineNumber: 2	  Type:	  Identifier
token: =               lineNumber: 2	  Type:	  Assign Operator
token: 5               lineNumber: 2	  Type:	  Number
token: ;               lineNumber: 2	  Type:	  Separating Character
token: float           lineNumber: 3	  Type:	  Fundamental type
token: y               lineNumber: 3	  Type:	  Identifier
token: =               lineNumber: 3	  Type:	  Assign Operator
token: 3.14            lineNumber: 3	  Type:	  Number
token: ;               lineNumber: 3	  Type:	  Separating Character
token: bool            lineNumber: 4	  Type:	  Fundamental type
token: flag            lineNumber: 4	  Type:	  Identifier
token: =               lineNumber: 4	  Type:	  Assign Operator
token: true            lineNumber: 4	  Type:	  Reserved Constant
token: ;               lineNumber: 4	  Type:	  Separating Character
token: char            lineNumber: 5	  Type:	  Fundamental type
token: c               lineNumber: 5	  Type:	  Identifier
token: =               lineNumber: 5	  Type:	  Assign Operator
token: '               lineNumber: 5	  Type:	  Error: illegal character 
token: a               lineNumber: 5	  Type:	  Identifier
token: '               lineNumber: 5	  Type:	  Error: illegal character 
token: ;               lineNumber: 5	  Type:	  Separating Character
token: if              lineNumber: 7	  Type:	  Flow Control
token: (               lineNumber: 7	  Type:	  Separating Character
token: x               lineNumber: 7	  Type:	  Identifier
token: >               lineNumber: 7	  Type:	  Comparison Operator
token: 3               lineNumber: 7	  Type:	  Number
token: )               lineNumber: 7	  Type:	  Separating Character
token: {               lineNumber: 7	  Type:	  Separating Character
token: x               lineNumber: 8	  Type:	  Identifier
token: =               lineNumber: 8	  Type:	  Assign Operator
token: x               lineNumber: 8	  Type:	  Identifier
token: +               lineNumber: 8	  Type:	  Arithmetic Operator
token: 2               lineNumber: 8	  Type:	  Number
token: ;               lineNumber: 8	  Type:	  Separating Character
token: }               lineNumber: 9	  Type:	  Separating Character
token: else            lineNumber: 9	  Type:	  Flow Control
token: {               lineNumber: 9	  Type:	  Separating Character
token: x               lineNumber: 10	  Type:	  Identifier
token: =               lineNumber: 10	  Type:	  Assign Operator
token: x               lineNumber: 10	  Type:	  Identifier
token: -               lineNumber: 10	  Type:	  Arithmetic Operator
token: 1               lineNumber: 10	  Type:	  Number
token: ;               lineNumber: 10	  Type:	  Separating Character
token: }               lineNumber: 11	  Type:	  Separating Character
token: while           lineNumber: 13	  Type:	  Flow Control
token: (               lineNumber: 13	  Type:	  Separating Character
token: x               lineNumber: 13	  Type:	  Identifier
token: >               lineNumber: 13	  Type:	  Comparison Operator
token: 0               lineNumber: 13	  Type:	  Number
token: )               lineNumber: 13	  Type:	  Separating Character
token: {               lineNumber: 13	  Type:	  Separating Character
token: x               lineNumber: 14	  Type:	  Identifier
token: =               lineNumber: 14	  Type:	  Assign Operator
token: x               lineNumber: 14	  Type:	  Identifier
token: -               lineNumber: 14	  Type:	  Arithmetic Operator
token: 1               lineNumber: 14	  Type:	  Number
token: ;               lineNumber: 14	  Type:	  Separating Character
token: }               lineNumber: 15	  Type:	  Separating Character
token: return          lineNumber: 17	  Type:	  Flow Control
token: 0               lineNumber: 17	  Type:	  Number
token: ;               lineNumber: 17	  Type:	  Separating Character
token: }               lineNumber: 18	  Type:	  Separating Character
